### ISSUE TITLE
Plugin don't work on SM 1.10

### ISSUE THREAD

**Issue by Z-RAY-Z** [nanociaglia/Mutes-friendly-knife-sound#1]
Hello, i was put this plugin on server with SourceMod (1.10.0.6460) by AlliedModders LLC.
Plugin don't mute knife sound when i type !mk. It don't work. And i have nothing in error_logs.

**Comment by nanociaglia** [comment]
Hello, did you try to compile it against sm 1.10? instead of using the 1.9 compiled version

**Comment by Z-RAY-Z** [comment]
I was compile it on SM 1.10, checked in server and don't get any result.

**Comment by nanociaglia** [comment]
Do you have any other plugin like sm_stopsounds?

**Comment by Z-RAY-Z** [comment]
I using this https://github.com/AgentWesker/StopMusic

**Comment by nanociaglia** [comment]
Maybe that plugin is causing an issue with my plugin. Try disabling the Music plugin and let me know.

**Comment by Z-RAY-Z** [comment]
I disabled Music plugin, changed map but knifemute still not work.

**Comment by nanociaglia** [comment]
Okey, gonna try it out using sm 1.10 in my dedicated server. I'll be back here when i fix this issue

**Comment by nanociaglia** [comment]
Before doing that i said above, please move every plugin you have (except the muteknife one) to the "disabled" folder. Restart your server. Once you restart it, try if my plugin works or not. If not, i'm gonna see what happens

**Comment by Z-RAY-Z** [comment]
I was disable all plugins and check on local-server:
https://youtu.be/OW8YZQThQew

**Comment by nanociaglia** [comment]
I got it. Please remember that you will always listen when you knife someone. Is the same with the plugin !stopsound, you will hear when you shoot. With the knifemute, if someone (of your team) knife you, you won't hear it. Same as if others players of the same team knife each other, the knife sound won't be displayed .

**Comment by nanociaglia** [comment]
Example:
https://youtu.be/KFt4EmgZTqU

**Comment by Z-RAY-Z** [comment]
I was check it again - and it works! Thank you for responses!
